finchcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('finches/', views.finches_index, name='finches_index'),
    path('finches/<int:finch_id>/', views.finches_detail, name='finches_detail'),
    path('finches/create/', views.FinchesCreate.as_view(), name='finches_create'),
    path('finches/<int:pk>/update/', views.FinchesUpdate.as_view(), name='finches_update'),
    path('finches/<int:pk>/delete/', views.FinchesDelete.as_view(), name='finches_delete'),
    path('finches/<int:finch_id>/add_feeding/', views.add_feeding, name='add_feeding'),
    path('stuffs/', views.StuffsIndex.as_view(), name='stuffs_index'),
    path('stuffs/create/', views.StuffsCreate.as_view(), name='stuffs_create'),
    path('stuffs/<int:pk>/', views.StuffsDetail.as_view(), name='stuffs_detail'),
    path('stuffs/<int:pk>/update', views.StuffsUpDate.as_view(), name='stuffs_update'),
    path('stuffs/<int:pk>/delete', views.StuffsDelete.as_view(), name='stuffs_delete'),
    path('accounts/signup/', views.signup, name='signup'),
    path('finches/<int:finch_id>/assoc_stuff/<int:stuff_id>/', views.assoc_stuff, name='assoc_stuff'),
]

main_app/models.py
from operator import mod
from random import choices
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


# Create your models here.

class Stuff(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=30)

    def __str__(self):
        return f'{self.color} {self.name}'

    def get_absolute_url(self):
        return reverse('stuffs_detail', kwargs={'pk': self.id})

class Finch(models.Model):
    name = models.CharField(max_length=100)
    colors = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    stuffs = models.ManyToManyField(Stuff)

    def __str__ (self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('finches_detail', kwargs={'finch_id': self.id })

class Feeding(models.Model):
    MEALS = (
    ('B', 'Breakfast'),
    ('D', 'Dinner'),
)
    date = models.DateField('feeding date')
    meal = models.CharField(max_length=1, choices=MEALS, default=MEALS[0][0])

    finch = models.ForeignKey(Finch, on_delete=models.CASCADE)

    def __str__ (self):
        return f'{self.get_meal_display()} on {self.date}'

    class Meta: 
        ordering = ['-date']

main_app/forms.py
from dataclasses import fields
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
    class Meta:
        model = Feeding
        fields = ('date', 'meal')

main_app/views.py
from curses.ascii import CR
from distutils.log import error
import imp
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render, redirect 
from .models import Finch, Stuff
from .forms import FeedingForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def finches_index(request):
    finches = Finch.objects.filter(user=request.user)
    return render(request, 'finches/index.html', {'finches': finches})

@login_required
def finches_detail(request, finch_id):
    finch = Finch.objects.get(id=finch_id)
    feeding_form = FeedingForm()
    stuffs = Stuff.objects.exclude(id__in=finch.stuffs.all().values_list('id'))
    return render(request, 'finches/detail.html', {
        'finch': finch, 'feeding_form': feeding_form, 'stuffs': stuffs
        })
@login_required
def add_feeding(request, finch_id):
    form = FeedingForm(request.POST)

    if form.is_valid():
        new_feeding = form.save(commit=False)
        new_feeding.finch_id = finch_id
        new_feeding.save()
    return redirect('finches_detail', finch_id=finch_id)

def signup(request):
    error_message = None
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('finches_index')
        else:
            error_message = 'Signup input invalid'
    form = UserCreationForm()
    context = { 'form': form, 'error': error_message }
    return render(request, 'registration/signup.html', context )

def assoc_stuff(request, finch_id, stuff_id):
    Finch.objects.get(id=finch_id).stuffs.add(stuff_id)
    return redirect('finches_detail', finch_id=finch_id)

class FinchesCreate(LoginRequiredMixin, CreateView):
    model = Finch
    fields = ('name', 'type', 'colors')

    def form_valid(self, form): 
        form.instance.user = self.request.user
        return super().form_valid(form)

class FinchesUpdate(LoginRequiredMixin, UpdateView):
    model = Finch
    fields = ('type', 'colors')

class FinchesDelete(LoginRequiredMixin, DeleteView):
    model = Finch
    success_url = '/finches/'

class StuffsIndex(LoginRequiredMixin, ListView):
    template_name = 'stuffs/index.html'
    model = Stuff

class StuffsCreate(LoginRequiredMixin, CreateView):
    model = Stuff
    fields = ('name', 'color')

class StuffsDetail(LoginRequiredMixin, DetailView):
    template_name = 'stuffs/detail.html'
    model = Stuff

class StuffsDelete(LoginRequiredMixin, DeleteView):
    model = Stuff
    success_url = '/stuffs/'

class StuffsUpDate(LoginRequiredMixin, UpdateView):
    model = Stuff
    fields = ('name', 'color')

main_app/templates/about.html
{% extends 'base.html' %}

{% block title %}
About | Finch Collector
{% endblock %}

{% block content %}
<h1>About</h1>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

</head>

<body>
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <ul>
                    <li>
                        <a href="{% url 'home' %}" class="left brand-logo"> FinchCollector</a>
                    </li>
                </ul>
                <ul class="right">
                    <li><a href="{% url 'about' %}">About</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'finches_index' %}">View All My Finches</a></li>
                    <li><a href="{% url 'finches_create' %}">Add a New Finch</a></li>
                    <li><a href="{% url 'stuffs_create' %}">Add New Item</a></li>
                    <li><a href="{% url 'stuffs_index' %}">View Items</a></li>
                    <li><a href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                    <li><a href="{% url 'login' %}">Login</a></li>
                    <li><a href="{% url 'signup' %}">Signup</a></li>
                    {% endif %}


                </ul>
            </div>
        </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer">
        <div class="right">
            All Rights Reserved, © 2022 Finch Collector
        </div>
    </footer>
</body>

</html>

main_app/templates/finches/detail.html
{% extends 'base.html' %}

{% block title %}

Details for {{ finch.name }} | Finch Collector

{% endblock %}

{% block content %}

<h1>Finch Details</h1>

<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ finch.name }}</span>
                <p>Type: {{finch.type }}</p>
                <p>Colors: {{finch.colors}}</p>
            </div>
            <div class="card-action">
                <a href="{% url 'finches_update' finch.id %}"> Edit</a>
                <a href="{% url 'finches_delete' finch.id %}"> Delete</a>
            </div>
        </div>
    </div>

    <div class="col s6">
        <form action="{% url 'add_feeding' finch.id %}" method="POST">
            {% csrf_token %}
            {{ feeding_form.as_p }}
            <input class="btn green" type="submit" value="Add Feeding">
        </form>

        <table class="striped">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Meal</th>
                </tr>
            </thead>
            <tbody>
                {% for feeding in finch.feeding_set.all %}
                <tr>
                    <td>{{ feeding.date }}</td>
                    <td>{{ feeding.get_meal_display }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<hr>

<div class="row">
    <div class="col s6">
        <h3>{{ finch.name }}'s Itmes</h3>
        {% if finch.stuffs.count %}
        {% for stuff in finch.stuffs.all %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">
                    A <span class="{{ stuff.color.lower }}-text">{{ stuff.color.capitalize }} </span>{{ stuff.name }}
                </span>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h5> No Items </h5>
        {% endif %}
    </div>
    <div class="col s6">
        <h3>Available Items</h3>
        {% if stuffs.count %}
        {% for stuff in stuffs.all %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">
                    A <span class="{{ stuff.color.lower }}-text">{{ stuff.color.capitalize }} </span>{{ stuff.name }}
                </span>
            </div>
            <div class="card-action">
                <form action="{% url 'assoc_stuff' finch.id stuff.id %}" method="POST">
                    {% csrf_token %}
                    <input class="btn blue" type="submit" value="Add">
                </form>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h4>None</h4>
        {% endif %}
    </div>

</div>
<script>
    const dateEl = document.getElementById('id_date');
    const selectEl = document.getElementById('id_meal');

    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });

    M.FormSelect.init(selectEl);
</script>


{% endblock %}

main_app/templates/finches/index.html
{% extends 'base.html' %}

{% block title %}
Finches Index | Finch Collector
{% endblock %}

{% block content %}
<h1>Finches Index</h1>

{% for finch in finches %}
<a href="{% url 'finches_detail' finch.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ finch.name }}</span>
            <p>Colors: {{ finch.colors }} </p>
            <p>Type: {{ finch.type }}</p>
        </div>
    </div>
</a>


{% endfor %}



{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}

{% block title %}
Home | Finch Collector
{% endblock %}

{% block content %}
<h1>Home</h1>
{% endblock %}

main_app/templates/main_app/finch_confirm_delete.html
{% extends 'base.html' %}

{% block title %}

Are You Sure You Want to Delete {{ object.name }} | Finch Collector

{% endblock %}

{% block content %}

<h1>Are you sure you want to delete <span class="blue-text">{{ object.name }}</span>?</h1>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn red" type="submit" value="Yes - Delete">
    <a class="btn blue" href="{% url 'finches_detail' object.id %}"> No - Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/finch_form.html
{% extends 'base.html' %}

{% block title %}

Add a New Finch | Finch Collector
{% endblock %}

{% block content %}

{% if object %}
<h1>Edit {{ object.name }}'s Details</h1>
{% else %}
<h1>Add a New Finch</h1>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="{% if object %} Update {% else %} Add New Finch {% endif %}" class="btn green">
</form>

{% endblock %}

main_app/templates/main_app/stuff_confirm_delete.html
{% extends 'base.html' %}

{% block title %}

Are You Sure You Want to Delete {{ object.name }} | Finch Collector

{% endblock %}

{% block content %}

<h1>Are you sure you want to delete <span class="blue-text">{{ object.name }}</span>?</h1>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn red" type="submit" value="Yes - Delete">
    <a class="btn blue" href="{% url 'stuffs_detail' object.id %}"> No - Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/stuff_detail.html
{% extends 'base.html' %}

{% block title %}

Details for {{ object.name }} | Finch Collector

{% endblock %}

{% block content %}

<h1>Finch Stuff Detail</h1>

<div class="card">
    <div class="card-content">
        <span class="card-title">A <span class="{{object.color.lower}}-text">{{object.color.capitalize}} </span>
            {{object.name }} </span>
    </div>
    <div class="card-action">
        <a href="{% url 'stuffwithfinch_update' object.id %}">Edit</a>
        <a href="{% url 'stuffwithfinch_delete' object.id %}">Delete</a>
    </div>
</div>

{% endblock %}

main_app/templates/main_app/stuff_form.html
{% extends 'base.html' %}

{% block title %}

Add a New Item | Finch Collector

{% endblock %}

{% block content %}

{% if object %}
<h1>Edit <span class="{{object.color.lower}}-text">{{object.color.capitalize}}</span> {{ object.name.capitalize}} </h1>
{% else %}
<h1>Add New Item</h1>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" class="btn green">
</form>

{% endblock %}

main_app/templates/main_app/stuffwithfinch_confirm_delete.html
{% extends 'base.html' %}

{% block title %}

Are You Sure You Want to Delete {{ object.name }} | Finch Collector

{% endblock %}

{% block content %}

<h1>Are you sure you want to delete <span class="blue-text">{{ object.name }}</span>?</h1>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn red" type="submit" value="Yes - Delete">
    <a class="btn blue" href="{% url 'stuff_detail' object.id %}"> No - Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/stuffwithfinch_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
<h1>Edit <span class="{{object.color.lower}}-text">{{object.color.capitalize}}</span> {{ object.name.capitalize}} </h1>
{% else %}
<h1>Add New Item</h1>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" class="btn green">
</form>

{% endblock %}

main_app/templates/stuffs/detail.html
{% extends 'base.html' %}

{% block title %}

Details for {{ object.name }} | Finch Collector

{% endblock %}

{% block content %}

<h1>Finch Stuff Detail</h1>

<div class="card">
    <div class="card-content">
        <span class="card-title">A <span class="{{object.color.lower}}-text">{{object.color.capitalize}} </span>
            {{object.name }} </span>
    </div>
    <div class="card-action">
        <a href="{% url 'stuffs_update' object.id %}">Edit</a>
        <a href="{% url 'stuffs_delete' object.id %}">Delete</a>
    </div>
</div>

{% endblock %}

main_app/templates/stuffs/index.html
{% extends 'base.html' %}

{% block title %}
Stuffs Index | Finch Collector
{% endblock %}

{% block content %}

<h1>Finch Stuffs Index</h1>

{% for stuff in object_list %}

<a href="{% url 'stuffs_detail' stuff.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">A <span class="{{stuff.color.lower}}-text">{{stuff.color.capitalize}}</span>
                {{stuff.name }} </span>
        </div>
    </div>
</a>

{% endfor %}

{% endblock %}